Repository vishipayyallore/eshop-main, pull requests merged in 2022-07, with the labels that each got.

#23 Swamy/15may2022 architecture diagram other updates
  Documentation/Architecture.pptx
  Documentation/SessionsFirstLook/K8s_JustForUnderstanding.PNG
  Documentation/SessionsFirstLook/Session6.PNG
Labels: documentation

#24 Swamy/22jul2022 session7 updates
  .github/Readme.md
  .github/workflows/deploy-aks.yml
  Deploy/Readme.md
  Infrastructure/AKS/.terraform.lock.hcl
  Infrastructure/AKS/1-main.tf
  Infrastructure/AKS/2-variables.tf
  Infrastructure/AKS/3-create_aks.tf
  Infrastructure/Readme.md
Labels: documentation, enhancement

#31 Swamy/23jul2022 session7 updates
  .github/workflows/deploy-aks.yml
Labels: documentation

#34 Swamy/23jul2022 session7 updates
  .github/workflows/deploy-aks.yml
Labels: documentation, enhancement

#36 Swamy/23jul2022 session7 updates
  .github/workflows/deploy-aks.yml
  .gitignore
  Deploy/eshop-services.products.yaml
  Deploy/eshop-solution.yaml
  Readme.md
Labels: documentation, enhancement

#38 Swamy/23jul2022 session7 updates
  Infrastructure/AKS/3-create_aks.tf
Labels: documentation, enhancement

#37 agent_count adjustment
  Infrastructure/AKS/2-variables.tf
  Infrastructure/AKS/3-create_aks.tf
  README.md
Labels: enhancement

#39 restore orchestration version
  Infrastructure/AKS/3-create_aks.tf
Labels: bug

#40 bump
  Readme.md
Labels: documentation

#41 Swamy/23jul2022 session7 updates
  Infrastructure/AKS/3-create_aks.tf
Labels: enhancement

#43 Swamy/23jul2022 session7 updates
  Readme.md
Labels: documentation

#44 Swamy/23jul2022 session7 updates
  Readme.md
Labels: documentation

#46 Renamed the Readme.md file
  RM.md
Labels: documentation, enhancement

#47 Swamy/30jul2022 session7 workflow and other updates
  README.md
Labels: documentation, enhancement

#48 Swamy/30jul2022 session7 workflow and other updates
  .github/workflows/01-Scan-Terraform-Config.yml
  .github/workflows/02-Gated-Terraform-Build.yml
  .github/workflows/deploy-aks-v1.yml
  README.md
  RM.md
Labels: documentation, enhancement

#49 Swamy/30jul2022 session7 workflow and other updates
  .github/workflows/01-Scan-Terraform-Config.yml
  .github/workflows/02-Gated-Terraform-Build.yml
Labels: documentation, enhancement

#50 Swamy/30jul2022 session7 workflow and other updates
  .github/workflows/01-Scan-Terraform-eShop-Infra.yml
  .github/workflows/02-Gated-Build-eShop-Infra.yml
  .github/workflows/03-CI-Build-eShop-Infra.yml
  .github/workflows/05-deploy-aks.yml
  README.md
Labels: documentation, enhancement

#52 Swamy/30jul2022 session7 workflow and other updates
  .github/workflows/01-Scan-Terraform-eShop-Infra.yml
  .github/workflows/02-Gated-Build-eShop-Infra.yml
  .github/workflows/03-CI-Build-eShop-Infra.yml
  .github/workflows/04-Deploy-eShop-Infra-to-Azure.yml
  .github/workflows/05-Main-eShop-Infra-to-Azure.yml
  Documentation/Starter/S7/deploy-aks.yml
Labels: documentation, enhancement

#53 Swamy/30jul2022 session7 workflow and other updates
  .github/workflows/01-Scan-Terraform-eShop-Infra.yml
  .github/workflows/05-Main-eShop-Infra-to-Azure.yml
Labels: documentation, enhancement

#54 Swamy/30jul2022 session7 workflow and other updates
  .github/workflows/01-Scan-Terraform-eShop-Infra.yml
  .github/workflows/02-Gated-Build-eShop-Infra.yml
  .github/workflows/03-CI-Build-eShop-Infra.yml
  .github/workflows/04-Deploy-eShop-Infra-to-Azure.yml
  .github/workflows/05-Main-eShop-Infra-to-Azure.yml
Labels: documentation, enhancement
